### ISSUE TITLE
numeric-archaeology

### ISSUE THREAD

**Issue by dfunke** [CarlOrff/biblatex-archaeology#13]
It would be nice to also have a `numeric-archaeology` style similar to `authoryear-archaeology`. In particular I require the `preservelastauthor` option for a DFG proposal

**Comment by CarlOrff** [comment]
Sorry, missed this completely due to some bad default settings. From a technical point of view it should be not a big deal to generate a `numeric-archaeology` style. I am going to look at the code next week anyway trying to close some issues. Is there a real world example of such a style (guide lines, open access example or a scan you send me privately)? I have never used a numeric style but I suppose it has some options to choose from.

**Comment by dfunke** [comment]
I think [this](https://www.councilscienceeditors.org/wp-content/uploads/v26n4p122-123.pdf) is the article that the DFG guideline is based on

**Comment by CarlOrff** [comment]
Just added `numeric-comp-archaeology` (https://github.com/CarlOrff/biblatex-archaeology/commit/a087e8f9a34ef64d3ccc75666ccd0a299d4e693a).  Will ship with v. 1.4 in short.

**Comment by CarlOrff** [comment]
Added styles `rgk-numeric` and `rgzm-numeric`.
